// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<app.LoginResult>;

export function ClearCache():Promise<void>;

export function GetCurrentEmail():Promise<string>;

export function GetMessage(arg1:string,arg2:number):Promise<app.MessageDetailDTO>;

export function GetSavedEmail():Promise<string>;

export function GetSettings():Promise<app.SettingsDTO>;

export function HasAccounts():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function ListAccounts():Promise<Array<app.AccountDTO>>;

export function ListFolders():Promise<Array<app.FolderDTO>>;

export function ListMessages(arg1:string,arg2:number,arg3:number):Promise<Array<app.MessageSummaryDTO>>;

export function ListMessagesCached(arg1:string):Promise<Array<app.MessageSummaryDTO>>;

export function ListProviders():Promise<Array<app.ProviderDTO>>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<app.LoginResult>;

export function Logout():Promise<void>;

export function PeekAccountCache(arg1:string):Promise<app.AccountCacheDTO>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SaveSettings(arg1:app.SettingsDTO):Promise<void>;

export function SwitchAccount(arg1:string):Promise<app.LoginResult>;

export function TryAutoLogin():Promise<app.LoginResult>;

export function UpdateAccount(arg1:string,arg2:string,arg3:string):Promise<app.LoginResult>;
