// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3, arg4) {
  return window['go']['app']['MailApp']['AddAccount'](arg1, arg2, arg3, arg4);
}

export function ClearCache() {
  return window['go']['app']['MailApp']['ClearCache']();
}

export function GetCurrentEmail() {
  return window['go']['app']['MailApp']['GetCurrentEmail']();
}

export function GetMessage(arg1, arg2) {
  return window['go']['app']['MailApp']['GetMessage'](arg1, arg2);
}

export function GetSavedEmail() {
  return window['go']['app']['MailApp']['GetSavedEmail']();
}

export function GetSettings() {
  return window['go']['app']['MailApp']['GetSettings']();
}

export function HasAccounts() {
  return window['go']['app']['MailApp']['HasAccounts']();
}

export function IsLoggedIn() {
  return window['go']['app']['MailApp']['IsLoggedIn']();
}

export function ListAccounts() {
  return window['go']['app']['MailApp']['ListAccounts']();
}

export function ListFolders() {
  return window['go']['app']['MailApp']['ListFolders']();
}

export function ListMessages(arg1, arg2, arg3) {
  return window['go']['app']['MailApp']['ListMessages'](arg1, arg2, arg3);
}

export function ListMessagesCached(arg1) {
  return window['go']['app']['MailApp']['ListMessagesCached'](arg1);
}

export function ListProviders() {
  return window['go']['app']['MailApp']['ListProviders']();
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['app']['MailApp']['Login'](arg1, arg2, arg3, arg4);
}

export function Logout() {
  return window['go']['app']['MailApp']['Logout']();
}

export function PeekAccountCache(arg1) {
  return window['go']['app']['MailApp']['PeekAccountCache'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['app']['MailApp']['RemoveAccount'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['MailApp']['SaveSettings'](arg1);
}

export function SwitchAccount(arg1) {
  return window['go']['app']['MailApp']['SwitchAccount'](arg1);
}

export function TryAutoLogin() {
  return window['go']['app']['MailApp']['TryAutoLogin']();
}

export function UpdateAccount(arg1, arg2, arg3) {
  return window['go']['app']['MailApp']['UpdateAccount'](arg1, arg2, arg3);
}
